[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/cas3-core",
    "projects/cas3-jupyter",
]
exclude = [
    "projects/playground",
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"

