# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "cas3-cli",
    "cas3-jup",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false
