# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "cas3-jup"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
jupyter = "0.2.0"
